Untested changes

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -1,16 +1,66 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# Welcome to the monfresh laptop script!
+##############################################
+# Welcome to the mac developer laptop script!
 # Be prepared to turn your laptop (or desktop)
 # into an awesome development machine.
+##############################################
 
+##############################################
+#  Common bash setting and script functions
+##############################################
+
+#----------------------------------------------
+# Configure the mac environment
+#----------------------------------------------
+defaults write com.apple.finder AppleShowAllFiles YES; # show hidden files
+defaults write com.apple.dock persistent-apps -array; # remove icons in Dock
+defaults write com.apple.dock tilesize -int 36; # smaller icon sizes in Dock
+defaults write com.apple.dock autohide -bool true; # turn Dock auto-hidng on
+defaults write com.apple.dock autohide-delay -float 0; # remove Dock show delay
+defaults write com.apple.dock autohide-time-modifier -float 0; # remove Dock show delay
+defaults write com.apple.dock orientation right; # place Dock on the right side of screen
+defaults write NSGlobalDomain AppleShowAllExtensions -bool true; # show all file extensions
+killall Dock 2>/dev/null;
+killall Finder 2>/dev/null;
+
+#----------------------------------------------
+# Configure the shell
+#----------------------------------------------
+# Some specific hygine settings to configure the shell
+shopt -s extglob
+set -o errtrace
+set -o errexit
+# shellcheck disable=SC2154
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+# Die on failures
+set -e
+# set -x
+
+#----------------------------------------------
+# Functions for this shell
+#----------------------------------------------
+# Verify if the given command works/exists
+command_exists () {
+  type "$1" &> /dev/null ;
+}
+# Fancy echo helps to print the output to console
 fancy_echo() {
   local fmt="$1"; shift
 
   # shellcheck disable=SC2059
   printf "\n$fmt\n" "$@"
 }
-
+# Logging functions
+log()  { printf "%b\n" "$*"; }
+debug(){ log "\nDEBUG: $*\n" ; }
+fail() { log "\nERROR: $*\n" ; exit 1 ; }
+download(){ 
+  # do not fail, silent, ShowError, follow redirects, specify file name
+  fancy_echo "Inside download, about to curl ... %s" "$1"
+  curl -fsSL $1
+}
+#Create or append zshrc and any text files.
 append_to_file() {
   local file="$1"
   local text="$2"
@@ -28,181 +78,210 @@ append_to_file() {
   fi
 }
 
-# shellcheck disable=SC2154
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+#Init for this script
+# Install bash min version, zsh and make zsh as default shell for the system.
+init(){
+  # Ask for the administrator password upfront
+  sudo -v
 
-set -e
+  BASH_MIN_VERSION="3.2.25"
+    if
+      [[ -n "${BASH_VERSION:-}" &&
+        "$(\printf "%b" "${BASH_VERSION:-}\n${BASH_MIN_VERSION}\n" | LC_ALL=C \sort -t"." -k1,1n -k2,2n -k3,3n | \head -n1)" != "${BASH_MIN_VERSION}"
+      ]]
+    then
+      fancy_echo "BASH ${BASH_MIN_VERSION} required (you have $BASH_VERSION)"
+      exit 1
+    fi
+  if [ ! -d "$HOME/.bin/" ]; then
+    mkdir "$HOME/.bin"
+  fi
 
-if [ ! -d "$HOME/.bin/" ]; then
-  mkdir "$HOME/.bin"
-fi
+  if [ ! -f "$HOME/.zshrc" ]; then
+    touch "$HOME/.zshrc"
+  fi
 
-if [ ! -f "$HOME/.zshrc" ]; then
-  touch "$HOME/.zshrc"
-fi
+  case "$SHELL" in
+    */zsh) : ;;
+    *)
+      fancy_echo "Changing your shell to zsh ..."
+        chsh -s "$(which zsh)"
+      ;;
+  esac
+}
+# Usage for this script.
+usage()
+{
+  printf "%b" "
 
-# shellcheck disable=SC2016
-append_to_file "$HOME/.zshrc" 'export PATH="$HOME/.bin:$PATH"'
+Usage
+  mac_app_install.sh
 
-case "$SHELL" in
-  */zsh) : ;;
-  *)
-    fancy_echo "Changing your shell to zsh ..."
-      chsh -s "$(which zsh)"
-    ;;
-esac
+"
+}
 
-brew_install_or_upgrade() {
-  if brew_is_installed "$1"; then
-    if brew_is_upgradable "$1"; then
-      fancy_echo "Upgrading %s ..." "$1"
-      brew upgrade "$@"
+install_xcode() {
+
+  #Reference: 
+  #https://github.com/timsutton/osx-vm-templates/blob/ce8df8a7468faa7c5312444ece1b977c1b2f77a4/scripts/xcode-cli-tools.sh
+  #https://github.com/chcokr/osx-init/blob/master/install.sh
+  if ! command_exists $xcodeCmd; then
+    fancy_echo "About to install xcode CommandLineTools ....."
+    # on 10.9+, we can leverage SUS to get the latest CLI tools
+    if [ "$OSX_VERS" -ge 9 ]; then
+      fancy_echo "OSX_VERS > 9 install CommandLineTools ....."
+      # create the placeholder file that's checked by CLI updates' .dist code 
+      # in Apple's SUS catalog
+      touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
+      # find the CLI Tools update
+      PROD=$(softwareupdate -l | grep "\*.*Command Line" | head -n 1 | awk -F"*" '{print $2}' | sed -e 's/^ *//' | tr -d '\n')
+      # install it
+      softwareupdate -i "$PROD" -v
+    # on 10.7/10.8, we instead download from public download URLs, which can be found in
+    # the dvtdownloadableindex:
+    # https://devimages.apple.com.edgekey.net/downloads/xcode/simulators/index-3905972D-B609-49CE-8D06-51ADC78E07BC.dvtdownloadableindex
     else
-      fancy_echo "Already using the latest version of %s. Skipping ..." "$1"
+      [ "$OSX_VERS" -eq 7 ] && DMGURL=http://devimages.apple.com.edgekey.net/downloads/xcode/command_line_tools_for_xcode_os_x_lion_april_2013.dmg
+      [ "$OSX_VERS" -eq 8 ] && DMGURL=http://devimages.apple.com.edgekey.net/downloads/xcode/command_line_tools_for_osx_mountain_lion_april_2014.dmg
+      fancy_echo "OSX_VERS <=7 or 8 install CommandLineTools ....."
+      TOOLS=clitools.dmg
+      curl "$DMGURL" -o "$TOOLS"
+      TMPMOUNT=`/usr/bin/mktemp -d /tmp/clitools.XXXX`
+      hdiutil attach "$TOOLS" -mountpoint "$TMPMOUNT"
+      installer -pkg "$(find $TMPMOUNT -name '*.mpkg')" -target /
+      hdiutil detach "$TMPMOUNT"
+      rm -rf "$TMPMOUNT"
+      rm "$TOOLS"
+      exit
     fi
   else
-    fancy_echo "Installing %s ..." "$1"
-    brew install "$@"
+    echo "=== XCode CommandLineTools Installed at... `$xcodeCmd`"
   fi
+
 }
 
-brew_is_installed() {
-  brew list -1 | grep -Fqx "$1"
-}
-
-brew_is_upgradable() {
-  ! brew outdated --quiet "$1" >/dev/null
-}
-
-brew_tap_is_installed() {
-  brew tap | grep -Fqx "$1"
-}
-
-brew_tap() {
-  if ! brew_tap_is_installed "$1"; then
-    fancy_echo "Tapping $1..."
-    brew tap "$1" 2> /dev/null
-  fi
-}
-
-gem_install_or_update() {
-  if gem list "$1" | grep "^$1 ("; then
-    fancy_echo "Updating %s ..." "$1"
-    gem update "$@"
-  else
-    fancy_echo "Installing %s ..." "$1"
-    gem install "$@"
-  fi
-}
-
-brew_cask_expand_alias() {
-  brew cask info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
-}
-
-brew_cask_is_installed() {
-  local NAME
-  NAME=$(brew_cask_expand_alias "$1")
-  brew cask list -1 | grep -Fqx "$NAME"
-}
-
-app_is_installed() {
-  local app_name
-  app_name=$(echo "$1" | cut -d'-' -f1)
-  find /Applications -iname "$app_name*" -maxdepth 1 | egrep '.*' > /dev/null
-}
-
-brew_cask_install() {
-  if app_is_installed "$1" || brew_cask_is_installed "$1"; then
-    fancy_echo "$1 is already installed. Skipping..."
-  else
-    fancy_echo "Installing $1..."
-    brew cask install "$@"
-  fi
-}
-
-if ! command -v brew >/dev/null; then
-  fancy_echo "Installing Homebrew ..."
+install_homebrew(){
+  if ! command -v brew >/dev/null; then
+    fancy_echo "Installing Homebrew ..."
+    # Mac OS X Yosemite includes Ruby 2.0.0p481, so we will use this to install Homebrew
     curl -fsS \
       'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
 
     # shellcheck disable=SC2016
     append_to_file "$HOME/.zshrc" 'export PATH="/usr/local/bin:$PATH"'
-else
-  fancy_echo "Homebrew already installed. Skipping ..."
-fi
-
-fancy_echo "Updating Homebrew formulas ..."
-brew update
-
-brew_install_or_upgrade 'git'
-
-brew_tap 'gapple/services'
-
-brew_install_or_upgrade 'postgresql'
-fancy_echo 'Restarting postgres...'
-brew services restart postgresql
-
-brew_install_or_upgrade 'qt'
-
-brew_install_or_upgrade 'hub'
-# shellcheck disable=SC2016
-append_to_file "$HOME/.zshrc" 'eval "$(hub alias -s)"'
-
-append_to_file "$HOME/.gemrc" 'gem: --no-document'
-
-if ! command -v rbenv >/dev/null; then
-  if ! command -v rvm >/dev/null; then
-    fancy_echo 'Installing RVM and the latest Ruby...'
-    curl -L https://get.rvm.io | bash -s stable --ruby --auto-dotfiles --autolibs=enable
-    . ~/.rvm/scripts/rvm
   else
-    local_version="$(rvm -v 2> /dev/null | awk '$2 != ""{print $2}')"
-    latest_version="$(curl -s https://raw.githubusercontent.com/wayneeseguin/rvm/stable/VERSION)"
-    if [ "$local_version" != "$latest_version" ]; then
-      fancy_echo 'Upgrading RVM...'
-      rvm get stable --auto-dotfiles --autolibs=enable --with-gems="bundler"
+    fancy_echo "Homebrew already installed. Skipping ..."
+  fi
+}
+
+install_rrcup(){
+  #Git clone all the dot files
+  if [ ! -d "$HOME/mac-dotfiles/" ]; then
+    git clone $dotfiles_url ~/mac-dotfiles
+    fancy_echo "Moving to mac-dotfiles ..."
+    cd ~/mac-dotfiles
+  else
+    fancy_echo "Moving to mac-dotfiles ..."
+    cd ~/mac-dotfiles
+    git fetch
+    git checkout feature/v1 
+    git pull
+  fi
+  env RCRC=$HOME/mac-dotfiles/dotfiles/rcrc
+  brew tap thoughtbot/formulae
+  brew install rcm
+  rcup -d ~/mac-dotfiles/dotfiles -v
+}
+
+install_rvm(){
+  if ! command -v rbenv >/dev/null; then
+    if ! command -v rvm >/dev/null; then
+      fancy_echo 'Installing RVM and the latest Ruby...'
+      curl -L https://get.rvm.io | bash -s stable --ruby --auto-dotfiles --autolibs=enable
+      . ~/.rvm/scripts/rvm
+      #Fixing this issue for zsh
+      #http://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm
+      # https://github.com/rvm/rvm/issues/3212
+      append_to_file "$HOME/.zshrc" 'export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting'
+      # Verify RVM installation by running, which returns 'rvm is a function'
+      type rvm | head -1
+      fancy_echo "Verified rvm is a function ....."
+      #Installing few more rubies with rvm
+      rvm list
+      #rvm get stable
+      rvm install 1.9.3-p194
+      #rvm install 2.2.2
+      # for octopress
+      #rvm use 1.9.3-p194
+      rvm use 2.2.2
+      rvm default 2.2.2
     else
-      fancy_echo "Already using the latest version of RVM. Skipping..."
+      local_version="$(rvm -v 2> /dev/null | awk '$2 != ""{print $2}')"
+      latest_version="$(curl -s https://raw.githubusercontent.com/wayneeseguin/rvm/stable/VERSION)"
+      if [ "$local_version" != "$latest_version" ]; then
+        fancy_echo 'Upgrading RVM...'
+        rvm get stable --auto-dotfiles --autolibs=enable --with-gems="bundler"
+      else
+        fancy_echo "Already using the latest version of RVM. Skipping..."
+      fi
     fi
   fi
-fi
+}
 
-fancy_echo 'Updating Rubygems...'
-gem update --system
 
-gem_install_or_update 'bundler'
+#Install or update ruby gems from a list of items.
+install_ruby_gem() {
+  if gem list "$1" | grep "^$1 ("; then
+    fancy_echo "Updating %s ..." "$1"
+    gem update "$@"
+    fancy_echo "Configuring Bundler ..."
+    number_of_cores=$(sysctl -n hw.ncpu)
+    bundle config --global jobs $((number_of_cores - 1))
+  else
+    fancy_echo "Installing %s ..." "$1"
+    gem install "$@"
+  fi
+}
+update_gem_system(){
+  gem update --system
+}
+#----------------------------------------------
+# End of Functions for this shell
+#----------------------------------------------
 
-fancy_echo "Configuring Bundler ..."
-  number_of_cores=$(sysctl -n hw.ncpu)
-  bundle config --global jobs $((number_of_cores - 1))
+##############################################
+#  Start executing the main steps
+##############################################
 
-brew_install_or_upgrade 'heroku-toolbelt'
+# Initialize, configure and change the shell to zsh.
+fancy_echo "Initialize your shell to zsh ..."
+init
+install_xcode
+install_homebrew
+brew tap homebrew/bundle
+install_rrcup
+install_rvm
+install_ruby_gem 'bundler'
+install_ruby_gem 'cocoapods'
+#update_gem_system
 
-brew_tap 'caskroom/cask'
+#########################################################
+#  Start installing all applications using homebrew
+#########################################################
+# We will use the brew file method to install all required command-line tools
+# More details here: https://robots.thoughtbot.com/brewfile-a-gemfile-but-for-homebrew
+# Don't have time to go through the reference, just follow the instructions below
+# To use the Brewfile, tap homebrew/bundle (one time)
+fancy_echo "Start Brewfile ..."
 
-brew_install_or_upgrade 'brew-cask'
+# use the Brewfile which has all required tools
+brew bundle --file=Brewfile-common
+brew bundle --file=Brewfile-app-dev
 
-brew_tap 'caskroom/versions'
+#if [ -f "$HOME/.laptop.local" ]; then
+#  . "$HOME/.laptop.local"
+#fi
 
-brew_cask_install 'flux'
-brew_cask_install 'github'
-brew_cask_install 'sublime-text3'
-
-if [ -f "$HOME/.laptop.local" ]; then
-  . "$HOME/.laptop.local"
-fi
-
-append_to_file "$HOME/.rvmrc" 'rvm_auto_reload_flag=2'
-
-# display pwd in orange, current ruby version or gemset in green,
-# and set prompt character to $
-# shellcheck disable=SC2016
-append_to_file "$HOME/.zshrc" 'precmd () { PS1="%{%F{166}%}[%~] %{%F{65}%}$(rvm-prompt) %{%f%}$ " }'
-
-# display directories and files in different colors when running ls
-append_to_file "$HOME/.zshrc" 'export CLICOLOR=1;'
-append_to_file "$HOME/.zshrc" 'export LSCOLORS=exfxcxdxbxegedabagacad;'
-
-if [ ! -f "$HOME/.ssh/github_rsa.pub" ]; then
-  open ~/Applications/GitHub.app
-fi
+#if [ ! -f "$HOME/.ssh/github_rsa.pub" ]; then
+#  open ~/Applications/GitHub.app
+#fi
